# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ecf1c6958fed5f26bb8eb2ad638cd9abaff03eea27c5e1cf755462064e3df629636020ebf90e5676e7400be1220efa31d9044b6c6ecd4772890bf1e8ea2cbd04

test:
  secret_key_base: 31d896629e3c6b89f9fb8c6e4c94ce42e5ce36b9017eb3905ea3e9f4a8c93052f38cc7e2f1eba7fc32695498d69fe22c93e53f4b0db0a1c04d65cdabb292cdbc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
